### ISSUE TITLE
Full DOIs?

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/open-forcefield-data#4]
@bmanubay - Niels in the Gilson lab remarks that the filename field seems to be part but not all of the DOI. Is there a way to get the full DOI? Particularly, he says:

> 1. The filename field seems to be a DOI, except that the first half of the DOI (registry/registrant) is missing.   I can google the filename and usually get to the published article, but is there some way to get the full DOI directly?
> 
> For instance, the first line here:  
> https://github.com/open-forcefield-group/open-forcefield-data/blob/master/Binary-Mixtures/Property%20data/eme_bin.csv (is that where I should be looking on github?) says ... j.jct.2005.03.012, but the full DOI is 10.1016/j.jct.2005.03.012

**Comment by bmanubay** [comment]
Hey @davidlmobley 

Unfortunately that is the information that ThermoPyL provides for filename when the data is pulled down. I looked into finding some way to generate DOI from these abbreviated article titles (like a Python module or something), but couldn't find anything.

**Comment by jchodera** [comment]
Probably a good question for Ken Kroenlein?  They should be documenting that.  

Note:
- The link to the original ThermoML standard description is broken on [this page](http://trc.nist.gov/ThermoML.html): Click on "Pure Appl. Chem., 2006, 78, 541-612" (ThermoML Recommendations 2006)
- That paper is [here](http://trc.nist.gov/ThermoMLRecommendations.pdf) but doesn't mention anything about truncated DOIs---it suggests full DOIs are stored in the `sDOI` field.
