### ISSUE TITLE
Proposed updates to SMIRFF format

### ISSUE THREAD

**Issue by jchodera** [openforcefield/open-forcefield-data#9]
To better take advantage of the existing [forcefield parameter assignment code from OpenMM](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py), I wanted to propose a modification to the SMIRFF format.

We would take this:

```
# SMARFF (SMARTS Force Field) mockup1.0 for alkanes, ethers, and alcohols
# Date: Tue May  3 2016
# Author: C. I. Bayly, OpenEye Scientific Software
# This mockup is based on frcmod.Frosst_AlkEthOH, the minimal subset of parm99/parm@Frosst
# required for alkanes, ethers, and alcohols (excluding ketals and 3-memb-rings)
#
# masses
[#1]     parMass  (  1.008 )   parNum m01 {from parm99}
[#6]     parMass  ( 12.01  )   parNum m02 {from parm99}
[#8]     parMass  ( 16.00  )   parNum m03 {from parm99}

# bonds
[#6X4]-[#6X4]    parBond  (1.526, 310.0) parNum b001 {CT-CT from frcmod.Frosst_AlkEthOH}
[#6X4]-[#1]      parBond  (1.090, 340.0) parNum b002 {CT-H_ from frcmod.Frosst_AlkEthOH}
[#6X4]-[O&X2&H1] parBond  (1.410, 320.0) parNum b003 {CT-OH from frcmod.Frosst_AlkEthOH}
[#6X4]-[O&X2&H0] parBond  (1.370, 320.0) parNum b004 {CT-OS from frcmod.Frosst_AlkEthOH}
[#8X2]-[#1]      parBond  (0.960, 553.0) parNum b005 {OH-HO from frcmod.Frosst_AlkEthOH}

# angles
[a,A]-[#6X4]-[a,A]   parAng (109.50, 50.0) parNum a001 {consensus matches all X-Csp3-X}
[#1]-[#6X4]-[#1]     parAng (109.50, 35.0) parNum a002 {H1-CT-H1 from frcmod.Frosst_AlkEthOH}
[#6X4]-[#6X4]-[#6X4] parAng (109.50, 40.0) parNum a003 {CT-CT-CT from frcmod.Frosst_AlkEthOH}
[#8X2]-[#6X4]-[#8X2] parAng (109.50, 70.0) parNum a004 {O_-CT-O_ from frcmod.Frosst_AlkEthOH}
[#6X4]-[#8X2]-[#1]   parAng (108.50, 55.0) parNum a005 {CT-OH-HO from frcmod.Frosst_AlkEthOH}
[#6X4]-[#8X2]-[#6X4] parAng (109.50, 60.0) parNum a006 {CT-OS-CT from frcmod.Frosst_AlkEthOH}

# torsions
[a,A]-[#6X4]-[#6X4]-[a,A]   parTor ( (9, 1.40, 0.0, 3) ) parNum t0001 {X -CT-CT-X from frcmod.Frosst_AlkEthOH}
[a,A]-[#6X4]-[#8X2]-[#1]    parTor ( (3, 0.50, 0.0, 3) ) parNum t0002 {X -CT-OH-X from frcmod.Frosst_AlkEthOH}
[a,A]-[#6X4]-[#8X2]-[!#1]   parTor ( (3, 1.15, 0.0, 3) ) parNum t0003 {X -CT-OS-X from frcmod.Frosst_AlkEthOH}
[#1]-[#6X4]-[#6X4]-[#1]     parTor ( (1, 0.15, 0.0, 3) ) parNum t0004 {HC-CT-CT-HC from frcmod.Frosst_AlkEthOH}
[#1]-[#6X4]-[#6X4]-[#6X4]   parTor ( (1, 0.16, 0.0, 3) ) parNum t0005 {HC-CT-CT-CT from frcmod.Frosst_AlkEthOH}

[#6X4]-[#6X4]-[#8X2]-[#1]   parTor ( (1, 0.16, 0.0, 3),
                                     (1, 0.25, 0.0, 1) ) parNum t0006 {HO-OH-CT-CT from frcmod.Frosst_AlkEthOH}

[#6X4]-[#6X4]-[#6X4]-[#6X4] parTor ( (1, 0.18,   0., 3),
                                     (1, 0.25, 180., 2),
                                     (1, 0.20, 180., 1) ) parNum t0007 {CT-CT-CT-CT from frcmod.Frosst_AlkEthOH}

[#6X4]-[#6X4]-[#8X2]-[#6X4] parTor ( (1, 0.383,  0., 3),
                                     (1, 0.1,  180., 2) ) parNum t0008 {CT-CT-OS-CT from frcmod.Frosst_AlkEthOH}

[#6X4]-[#8X2]-[#6X4]-[O&X2&H0] parTor ( (1, 0.10,   0., 3),
                                     (1, 0.85, 180., 2),
                                     (1, 1.35, 180., 1) ) parNum t0009 {CT-OS-CT-OS from frcmod.Frosst_AlkEthOH}

[#8X2]-[#6X4]-[#6X4]-[#8X2] parTor ( (1, 0.144,  0., 3),
                                     (1, 0.175,  0., 2) ) parNum t0010 {O_-CT-CT-O_ from frcmod.Frosst_AlkEthOH}

[#8X2]-[#6X4]-[#6X4]-[#1]   parTor ( (1, 0.00, 0.0, 3),
                                     (1, 0.25, 0.0, 1) ) parNum t0011 {H_-CT-CT-O_ from frcmod.Frosst_AlkEthOH, note parm@Frosst discrepancy with H2,H3-CT-CT-O_ }

# improper torsions
# right now none so placeholder for unrelated chemistry is provided to show form
[a,A]~[#6X3]([a,A])~[OX1]       parImpr (10.5, 180., 2 )  parNum i001 {X -X -C -O  from frcmod.Frosst_AlkEthOH}
[a,A]~[#6X3]([a,A])~[#6X3]      parImpr ( 1.1, 180., 2 )  parNum i002 {CA-CA-CA-CT from frcmod.Frosst_AlkEthOH}
[a,A]~[#6X3]([a,A])~[#1}        parImpr ( 1.1, 180., 2 )  parNum i003 {X -X -C_-H_ from frcmod.Frosst_AlkEthOH}

# vdW
[#1]                            parVdw ( 1.4870, 0.0157 ) parNum v001 {making HC the generic hydrogen}
[$([#1]-C)]                     parVdw ( 1.4870, 0.0157 ) parNum v002 {HC from frcmod.Frosst_AlkEthOH}
[$([#1]-C-[#7,#8,F,#16,Cl,Br])] parVdw ( 1.3870, 0.0157 ) parNum v003 {H1 from frcmod.Frosst_AlkEthOH}
[$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]
                                parVdw ( 1.2870, 0.0157 ) parNum v004 {H2 from frcmod.Frosst_AlkEthOH}
[$([#1]-C(-[#7,#8,F,#16,Cl,Br])(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]
                                parVdw ( 1.1870, 0.0157 ) parNum v005 {H3 from frcmod.Frosst_AlkEthOH}
[#1$(*-[#8])]                   parVdw ( 0.0000, 0.0000 ) parNum v006 {HO from frcmod.Frosst_AlkEthOH}

[#6]                            parVdw ( 1.9080, 0.1094 ) parNum v007 {making CT the generic carbon}
[#6X4]                          parVdw ( 1.9080, 0.1094 ) parNum v008 {CT from frcmod.Frosst_AlkEthOH}

[#8]                            parVdw ( 1.6837, 0.1700 ) parNum v009 {making OS the generic oxygen}
[#8X2]                          parVdw ( 1.6837, 0.1700 ) parNum v010 {OS from frcmod.Frosst_AlkEthOH}
[OX2+0$(*-[#1])]                parVdw ( 1.7210, 0.2104 ) parNum v011 {OH from frcmod.Frosst_AlkEthOH}
```

and turn it into this:

``` XML
<!-- SMARFF (SMARTS Force Field) mockup1.0 for alkanes, ethers, and alcohols -->
<Date>Date: Tue May  3 2016</Date>
<Author>C. I. Bayly, OpenEye Scientific Software</Author>
<!-- This mockup is based on frcmod.Frosst_AlkEthOH, the minimal subset of parm99/parm@Frosst -->
<!-- required for alkanes, ethers, and alcohols (excluding ketals and 3-memb-rings) -->

<AtomMasses>
  <AtomMass smirks="[#1]" mass="1.008" parNum="m01"/> <!-- from parm99 -->
  <AtomMass smirks="[#1]" mass="1.008" parNum="m02"/> <!-- from parm99 -->
  <AtomMass smirks="[#1]" mass="1.008" parNum="m03"/> <!-- from parm99 -->
</AtomMasses>
<HarmonicBondForce>
   <Bond smirks="[#6X4]-[#6X4]" length="1.626" k="310.0"/> <!-- CT-CT from frcmod.Frosst_AlkEthOH -->
   <Bond smirks="[#6X4]-[#1]" length="1.090" k="340.0"/> <!-- CT-H_ from frcmod.Frosst_AlkEthOH -->
   <Bond smirks="[#6X4]-[O&amp;X2&amp;H1]" length="1.410" k="320.0"/> <!-- CT-OH from frcmod.Frosst_AlkEthOH -->
   <Bond smirks="[#6X4]-[O&amp;X2&amp;H0]" length="1.370" k="320.0"/> <!--CT-OS from frcmod.Frosst_AlkEthOH -->
   <Bond smirks="[#8X2]-[#1]" length="0.960" k="553.0"/> <!-- OH-HO from frcmod.Frosst_AlkEthOH -->
</HarmonicBondForce>
<HarmonicAngleForce>
   <Angle smirks="[a,A]-[#6X4]-[a,A]" angle="109.50" k="50.0"/> <!-- consensus matches all X-Csp3-X -->
   <Angle smirks="[#1]-[#6X4]-[#1]" angle="109.50" k="35.0"/> <!-- H1-CT-H1 from frcmod.Frosst_AlkEthOH -->
   <Angle smirks="[#6X4]-[#6X4]-[#6X4]" angle="109.50" k="40.0"/> <!-- CT-CT-CT from frcmod.Frosst_AlkEthOH -->
   <Angle smirks="[#8X2]-[#6X4]-[#8X2]" angle="109.50" k="70.0"/> <!-- O_-CT-O_ from frcmod.Frosst_AlkEthOH -->
   <Angle smirks="[#6X4]-[#8X2]-[#1]" angle="108.50" k="55.0"/> <!-- CT-OH-HO from frcmod.Frosst_AlkEthOH -->
   <Angle smirks="[#6X4]-[#8X2]-[#6X4]" angle="109.50" k="60.0"/> <!-- CT-OS-CT from frcmod.Frosst_AlkEthOH -->
</HarmonicAngleForce>
<PeriodicTorsionForce>
   <Proper smirks="[a,A]-[#6X4]-[#6X4]-[a,A]" periodicity1="3" phase1="0.0" k1="1.40"/> <!-- X -CT-CT-X from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[a,A]-[#6X4]-[#8X2]-[#1]" periodicity1="3" phase1="0.0" k1="0.50"/> <!--X -CT-OH-X from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[a,A]-[#6X4]-[#8X2]-[!#1]" periodicity1="3" phase1="00" k1="1.15"/> <!-- X -CT-OS-X from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[#1]-[#6X4]-[#6X4]-[#1]" periodicity1="3" phase1="0.0" k1="0.15"/> <!-- HC-CT-CT-HC from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[#1]-[#6X4]-[#6X4]-[#6X4]" periodicity1="3" phase1="0.0" k1="0.16"/> <!-- HC-CT-CT-CT from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[#6X4]-[#6X4]-[#8X2]-[#1]" periodicity1="3" phase1="0.0" k1="0.16" periodiity2="1" phase2="0.0" k2="0.25"/> <!-- HO-OH-CT-CT from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[#6X4]-[#6X4]-[#6X4]-[#6X4]" periodicity1="3" phase1="0.0" k1="0.18" periodicity2="2" phase2="180.0" k2="0.25" periodicity3="1" phase3="180.0" k3="0.20"/> <!-- CT-CT-CT-CT from frcmod.Frosst_AlkEthOH -->
   <Proper smirks="[#6X4]-[#6X4]-[#8X2]-[#6X4]" periodicity1="3" phase1="0.0" k1="0.383" periodicity2="2" phase2="180.0" k2="0.1"/> <!-- CT-CT-OS-CT from frcmod.Frosst_AlkEthOH -->
...
   <Improper smirks="[a,A]~[#6X3]([a,A])~[OX1]" periodicity1="2" phase1="180.0" k1="10.5"/> <!-- X -X -C -O  from frcmod.Frosst_AlkEthOH -->
...
</PeriodicTorsionForce>
<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
   <Atom smirks="[#1]" sigma="1.4870" epsilon="0.0157"/> <!-- making HC the generic hydrogen -->
   <Atom smirks="[$([#1]-C)]" sigma="1.4870" epsilon="0.0157"/> <!-- HC from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-C-[#7,#8,F,#16,Cl,Br])]]" sigma="1.3870" epsilon="0.0157"/> <!-- H1 from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]" sigma="1.2870" epsilon="0.0157"/> <!--H2 from frcmod.Frosst_AlkEthOH -->
...
</NonbondedForce>
```

**Comment by jchodera** [comment]
Looks like I may have to [escape some characters](http://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents) in the XML.

**Comment by davidlmobley** [comment]
Bayly discussion:
- Yes, this will work
- But, it would be nice not to have to type all of the extra quotes, brackets, etc. as it will slow us down 
- But, yes, we would like to avoid extra implementation time handling converters
- So, maybe there is a middle ground?

JDC will explore slightly over next several days within his group. 

How to handle bond order?
- Bond order lines have length1/k1, length2/k2, length3/k3...?
- Torsions will have ~ between (for the middle bond of) things which means any type of bond

Key will just be getting fractional bond orders, which will probably happen in 2017.

**Comment by davidlmobley** [comment]
There will be a second version of this file that has:
- For each parameter, a multiplicative factor a where (parameter)/a gives the minimum search value and (parameter)*a gives the maximum search value (specifying the prior)
- The starting search value for each parameter

**Comment by davidlmobley** [comment]
The XML files also have to be able to handle macros; see this e-mail from Christopher Bayly:

> Amigos (particularly John),
> 
> I talked about this earlier: another xml specification we will need in SMIRFF is to be able to define a macro for certain common classes of substructure, for example
> [('halogen', '[$smallhals,$largehals]'), ('smallhals', '[F,Cl]'), ('largehals', '[Br,I])]
> 
> so that a smarts string of 'c[$halogen]' will turn into 'c[$([$([F,Cl]),$([Br,I])])]' with OESmartsLexReplace, c.f. this:
> 
> http://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OESmartsLexReplace.html
> 
> This will end up being critical for SMIRFFs beyond our toy set (though we will cut our teeth on them with the toy set).

**Comment by davidlmobley** [comment]
So, we're nearly done with this issue except:
- @jchodera needs to see (with his group - I raised issue on https://openforcefieldgroup.slack.com/archives/general/p1463682221000176) if there is a way to simplify the XML format for human typing
- We need to make sure we can handle macros

**Comment by davidlmobley** [comment]
@jchodera - I'm assuming we should probably declare this the final format and go with it? 

If so, then should I mark this issue as closed and raise a new issue (probably under open-forcefield-tools) with the final format info asking for this to be implemented for OpenMM? 

Obviously that's the long-term solution. As an interim solution, should I make a parser that will read these files and take a molecule, and create an AMBER `.prmtop` and `.crd` which we could then use to actually parameterize and simulate? Otherwise we'll soon be in a position where we might be able to generate these files but couldn't do anything with them.

**Comment by jchodera** [comment]
My current plan is to create a `SmartyForceField` class using a similar structure to the [`ForceField` class in `simtk.openmm.app`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py) that will implement this using the OpenEye toolkit.  This shouldn't take very long.

**Comment by jchodera** [comment]
Let's leave this issue open until we have a working example.

**Comment by jchodera** [comment]
To accomodate https://github.com/open-forcefield-group/open-forcefield-data/issues/9#issuecomment-220736079 what about

``` XML
<SmirksBinding replace="smallhals" smirks="[F,Cl]"/>
<Smirksbinding replace="largehals" smirks="[Br,I]"/>
<SmirksBinding replace="halogen" smirks="[$smallhals,$largehals]"/>
```

I'm happy to use other terms besides `SmirksBinding` and `replace` if that would be clearer.

**Comment by davidlmobley** [comment]
Looks good to me. I've forwarded to Bayly to see if he has any input.

On Mon, May 30, 2016 at 7:30 PM, John Chodera notifications@github.com
wrote:

> To accomodate #9 (comment)
> https://github.com/open-forcefield-group/open-forcefield-data/issues/9#issuecomment-220736079
> what about
> 
> <SmirksBinding replace="smallhals" smirks="[F,Cl]"/>
> <Smirksbinding replace="largehals" smirks="[Br,I]"/>
> <SmirksBinding replace="halogen" smirks="[$smallhals,$largehals]"/>
> 
> I'm happy to use other terms besides SmirksBinding and replace if that
> would be clearer.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/issues/9#issuecomment-222579421,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYbeMrEyz9QoJtFVCrv0Ag1JDYnYCks5qG502gaJpZM4IcrH4
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
@jchodera - from Christopher:

> Looks good, except in this case it really is SMARTS so how about
> `<SmartsBinding replace="smallhals" smarts="[F,Cl]"/>`
> etc.
> 
> Will the second keyword "smarts" potentially crash with other smarts-related keywords?

**Comment by jchodera** [comment]
Did something fail to come through in translation?

I can only guess he meant something like this:

``` XML
<SmartsReplace replace="smallhals" smarts="[F,Cl]"/>
<SmartsReplace replace="largehals" smarts="[Br,I]"/>
<SmartsReplace replace="halogen" smarts="[$smallhals,$largehals]"/>
```

**Comment by davidlmobley** [comment]
I copied and pasted, but, er, it looks like you actually mistyped. Your original code was:

``` XML
<SmirksBinding replace="smallhals" smirks="[F,Cl]"/>
```

which he amended to 

``` XML
<SmartsBinding replace="smallhals" smarts="[F,Cl]"/>
```

but as you note it should be

``` XML
<SmartsReplace replace="smallhals" smarts="[F,Cl]"/>
```

**Comment by jchodera** [comment]
Are you viewing this thread through Github?

https://github.com/open-forcefield-group/open-forcefield-data/issues/9#issuecomment-219326898

Or just via email?  I didn't see any amended code in your original response, though this came through---thanks!

Note that you can add `XML` after the three backticks to get markdown to render the XML with syntax highlighting!

**Comment by davidlmobley** [comment]
Github. And yeah, I had to edit once or twice to figure out the xml thing.

**Comment by jchodera** [comment]
@pgrinaway and @maxentile: Last chance for you to give comments here.

**Comment by jchodera** [comment]
@cbayly13 reminds us that we also want to (optionally) associate a unique `id` with each parameter, and allow the possibility for a `parent_id` as well.  This would look like

``` XML
<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
   <Atom smirks="[#1]" sigma="1.4870" epsilon="0.0157" id="00000"/> <!-- making HC the generic hydrogen -->
   <Atom smirks="[$([#1]-C)]" sigma="1.4870" epsilon="0.0157" id="00001" parent_id="00000"/> <!-- HC from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-C-[#7,#8,F,#16,Cl,Br])]]" sigma="1.3870" epsilon="0.0157 id="00002" parent_id="00000""/> <!-- H1 from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]" sigma="1.2870" epsilon="0.0157" id="00003" parent_id="00000"/> <!--H2 from frcmod.Frosst_AlkEthOH -->
...
</NonbondedForce>
```

Does that sound reasonable?  Is there any format we should adopt for the `id` to make this more human-comprehensible?

**Comment by pgrinaway** [comment]
This is looking good to me. I think these examples are quite readable and nice.

> associate a unique id with each parameter, and allow the possibility for a parent_id as well. This would look like

That would be good, especially given the planned atom type sampling scheme.

> Is there any format we should adopt for the id to make this more human-comprehensible?

I don't think this should be necessary. If need be, we can name parameters and have a translation table to add a `string_id` or something to the xml, but since this will be largely automated I think the human readability of the id is not as important. I don't feel very strongly on this though so if others have strongly differing opinions I'm fine with whatever you want.

**Comment by jchodera** [comment]
Thanks for the reminder about fractional bond orders. This can be easily extended to accommodate those, e.g.

``` XML
<HarmonicBondForce>
   <Bond smirks="[#6X4]~[#6X4]" length1="1.626" k1="310.0" length2="1.523" k2="450.0"/> <!-- CT-CT from frcmod.Frosst_AlkEthOH -->
</HarmonicBondForce>
```

**Comment by davidlmobley** [comment]
@jchodera :

> Does that sound reasonable? Is there any format we should adopt for the id to make this more human-comprehensible?

That looks quite reasonable to me. 

I thought about the format issue for a while, as I can imagine thinking it might be useful to be able to look at these parameter IDs and tell from them whether a parameter is closely related to another parameter, or to get some idea of their history. However, the more I think about it the more I realize this is not the point of parameter id's. We're really just after something **simple, short, numerical, and unique**, so serial numbers basically, exactly as you've written them.

**Comment by bas-rustenburg** [comment]
Just want to comment on something that @davidlmobley mentioned:

> if there is a way to simplify the XML format for human typing

I would recommend against modifying XML files by hand. XML is easy for computers to manipulate, but hard for humans to read and type. Errors are easily made. That is why there are [tons of tools available to edit xml files](https://en.wikipedia.org/wiki/Comparison_of_XML_editors). I wouldn't choose xml as a format if people will be typing these by hand. In that case, I would pick something like yaml.

**Comment by davidlmobley** [comment]
@bas-rustenburg - is there an easy way to go back and forth? @cbayly13  will undoubtedly want to spend a lot of time actually staring **at the parameters** and **at the smirks**, thinking about what they mean, and (potentially) tweaking things to see what happens if he does so, as this will help him develop a good automated framework for exploring smirks, especially. 

So, the key question which we were asking is, how do we make a good machine-readable format for OpenMM that also allows Christopher and others who actually want to look at the parameters and smirks and potentially tweak things to do so... i.e. do we need to make some sort of translator that makes these files into a nice viewable format, or is there some other format we should be using instead?

**Comment by bas-rustenburg** [comment]
It should be easy to use xml if everyone working with it can come up with a way to reliably handle it. Personally, I think the format is great and I would recommend we stick with XML. I just wanted to give a warning about the fact that it is easy to make invalid documents that can't be parsed, if you come up with a file by hand.

For example, the basic syntax of an xml file needs to have a document root. John's original example doesn't have a tag as the root of the document, and is therefore invalid and can't be parsed correctly. We could move everything inside of a `<Forcefield></Forcefield>` tag to fix that part. But this is the kind of stuff you'll easily run into.

**Comment by bas-rustenburg** [comment]
Though, manual editing can be a lot easier if you also have a tree viewer and validator on the side. I recommend something like this website. http://codebeautify.org/xmlviewer  . 

Edit: so, mildly adjusting my original point. XML is great, but if we hand-adjust files, we need to make sure to validate these since it is error prone. It'll save a lot of headaches.

**Comment by jchodera** [comment]
> I thought about the format issue for a while, as I can imagine thinking it might be useful to be able to look at these parameter IDs and tell from them whether a parameter is closely related to another parameter, or to get some idea of their history. However, the more I think about it the more I realize this is not the point of parameter id's. We're really just after something simple, short, numerical, and unique, so serial numbers basically, exactly as you've written them.

@pgrinaway and I just discussed this, and we think it would be much better if there was a simple tool that would parse the XML for you and plot the parameter lineage in a more human-readable way.  This could even be a module so that you can use it inside an IPython notebook. Would that work?

**Comment by pgrinaway** [comment]
> @pgrinaway and I just discussed this, and we think it would be much better if there was a simple tool that would parse the XML for you and plot the parameter lineage in a more human-readable way. This could even be a module so that you can use it inside an IPython notebook.

+1

**Comment by davidlmobley** [comment]
> @pgrinaway and I just discussed this, and we think it would be much better if there was a simple tool that would parse the XML for you and plot the parameter lineage in a more human-readable way. This could even be a module so that you can use it inside an IPython notebook. Would that work?

There are a lot of moving parts in this statement, so let me break them out a bit.

I totally agree that it would be useful to be able to see the parameter lineage, and parameter inter-relations, in a human-readable way (i.e. a genetic tree type representation or similar, maybe with smirks decorators), and yes, a module to do this within an IPython notebook would be just the right type of thing. 

BUT - "parse the XML for you..."; if the tool is going to get this lineage from the XML, does that mean that the full parameter lineage needs to be recoverable from the XML? If so, what exactly do we mean by "lineage"? In family trees and phylogenetic trees, the lineage is static, so there is no distinction between "lineage" and "history". However, here, the two are distinct -- for example, a parent parameter can die and be replaced by its offspring. 

My view is that we should be able to recover and visualize the "current" lineage (parameter relationships and tree) from the XML but if we want the history, this is a "trajectory" type property and we might want to store this information as it evolves just as we would data for a molecular simulation.

**Comment by pgrinaway** [comment]
> My view is that we should be able to recover and visualize the "current" lineage (parameter relationships and tree) from the XML but if we want the history, this is a "trajectory" type property and we might want to store this information as it evolves just as we would data for a molecular simulation.

I agree with this. I was thinking that the current lineage could be plotted with the XML as some kind of tree... we'd have to store the trajectory somewhere else, I'd assume.

**Comment by jchodera** [comment]
We can archive the history of sampled parameter sets as XML or something else, so we could presumably regenerate the evolution from this. But the parameters will always be hierarchical, so the "parentage" of any given parameter will always be present in the XML file if `id` and `parent_id` are present.

**Comment by davidlmobley** [comment]
Sounds great.

On Tue, Jun 7, 2016 at 5:06 PM, John Chodera notifications@github.com
wrote:

> We can archive the history of sampled parameter sets, so we could
> presumably regenerate the lineage from this. But the parameters will always
> be hierarchical.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/issues/9#issuecomment-224450822,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYfSx2oMichEK5q5eMMfuXk7ZFiErks5qJgeOgaJpZM4IcrH4
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
I'm closing this as it was implemented by https://github.com/open-forcefield-group/smarty/pull/24 and subsequently tested extensively. I'm opening a separate issue on the Smarty issue tracker which highlights a few (long-term) modifications we will make to the format that were raised in this thread.
